name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'src/**/*'
      - 'test/**/*'
      - '.github/workflows/**/*'
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm build
      - run: pnpm test

