name: Deploy to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  release:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build

      - name: Publish to NPM
        run: |
          pnpm config set //registry.npmjs.org/:_authToken ${{secrets.NPM_TOKEN}}
          pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
